# Generated by Django 5.1.3 on 2024-12-03 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=5)),
                ('gender', models.CharField(max_length=15)),
                ('procedure', models.CharField(max_length=200, null=True)),
                ('mobile', models.IntegerField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
                ('referred', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patientreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_reports', to='dev_pro.patientsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField(max_length=15)),
                ('otp', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
