# Generated by Django 5.1.3 on 2024-12-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0003_alter_patientsdetails_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreports',
            name='report_file',
            field=models.FileField(blank=True, upload_to='endo_files'),
        ),
    ]
