# Generated by Django 5.1.3 on 2024-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0003_alter_patientsdetails_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='speciality',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
