# Generated by Django 5.1.3 on 2024-12-06 06:47

import dev_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_pro', '0004_alter_patientreports_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreports',
            name='report_file',
            field=models.FileField(blank=True, upload_to=dev_pro.models.Patientreports.nameFile),
        ),
    ]
